# Generated by Django 5.1.6 on 2026-02-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('maintenance', 'Maintenance'), ('weather', 'Weather'), ('holiday', 'Holiday'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('activity', models.ForeignKey(blank=True, help_text='Leave blank to block ALL activities on this date', null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
