server {
    listen 80;
    server_name api.mangrovespot.in;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        root /var/www/mangrovespot_backend;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/mangrovespot_backend/gunicorn.sock;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
# After setup, run: sudo certbot --nginx -d api.mangrovespot.in
