# Generated by Django 5.1.6 on 2026-04-10 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_child_price_activityrule'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingitem',
            options={'ordering': ['visit_date']},
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='num_persons',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount collected online via Razorpay', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be collected at arrival', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('full', 'Full Payment'), ('half', 'Half Now, Half at Arrival')], default='half', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Visitor-selected arrival time (used when slot is null)', null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='num_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='Only set for activities using fixed time slots', null=True, on_delete=django.db.models.deletion.PROTECT, to='activities.timeslot'),
        ),
    ]
