# Generated by Django 5.1.6 on 2026-04-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount collected online via Razorpay (50% at booking)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be collected at arrival (remaining 50%)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('half', 'Half Now, Half at Arrival')], default='half', max_length=10),
        ),
    ]
