# Generated by Django 5.1.6 on 2026-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_amount_paid_alter_booking_balance_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('half', '50% now, 50% at arrival'), ('full', 'Full payment')], default='half', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
