# Generated by Django 5.1.6 on 2026-02-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('water', 'Water'), ('thrill', 'Thrill'), ('land', 'Land'), ('cultural', 'Cultural'), ('group_fun', 'Group Fun'), ('skill', 'Skill')], max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('duration', models.CharField(max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_type', models.CharField(choices=[('per_person', 'Per Person'), ('per_group', 'Per Group'), ('custom', 'Custom')], default='per_person', max_length=20)),
                ('extra_person_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_persons', models.PositiveIntegerField(default=1)),
                ('max_persons', models.PositiveIntegerField(default=10)),
                ('rules_text', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('requires_prebooking', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='activities.activity')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
