# Generated by Django 5.1.6 on 2026-04-10 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='child_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per child. Leave blank if same as adult.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ActivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='activities.activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
