# Generated by Django 5.1.6 on 2026-04-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_child_price_activityrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='closing_time',
            field=models.TimeField(default='17:00', help_text='Latest arrival time visitors can select when booking.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='opening_time',
            field=models.TimeField(default='06:30', help_text='Earliest arrival time visitors can select when booking.'),
        ),
    ]
