# Generated by Django 5.1.6 on 2026-04-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_closing_time_activity_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age in years required to participate. If set, the children counter is hidden on the booking form and a warning badge is shown on the activity card. Leave blank to allow all ages.', null=True),
        ),
    ]
